<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 8
        spacing: 8
        Image:
            id: showed_img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.1
        Button:
            text: 'Search image'
            size_hint_y: 0.1
            on_press: root.search_img()


<RootWidget>
    FirstScreen:
        id: first_screen
        name: 'first_screen'